// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPTI2.Data;

namespace ProjetoPTI2.Migrations
{
    [DbContext(typeof(ProjetoPTI2Context))]
    [Migration("20221026164554_CadastroFuncionario")]
    partial class CadastroFuncionario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoPTI2.Models.CadastroCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<DateTime>("Dt_cadastro");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.Property<int>("TipoLogin");

                    b.HasKey("Id");

                    b.ToTable("tbCliente");
                });

            modelBuilder.Entity("ProjetoPTI2.Models.CadastroFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<DateTime>("Dt_Contratacao");

                    b.Property<string>("Email");

                    b.Property<int>("Matricula");

                    b.Property<string>("Nome");

                    b.Property<int>("TipoLogin");

                    b.HasKey("Id");

                    b.ToTable("CadastroFuncionario");
                });
#pragma warning restore 612, 618
        }
    }
}
